import{i as l,S as m}from"./assets/vendor-8c59ed88.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))e(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function t(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(s){if(s.ep)return;s.ep=!0;const r=t(s);fetch(s.href,r)}})();const u="44377249-dc3d438c16ab3b76144728d61",p=document.getElementById("photos_input");function d(o,n){const t=new URLSearchParams({key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:200});return fetch(`https://pixabay.com/api/?${t.toString()}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(!e.hits||e.hits.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"400px",color:"#b90e0a",messageColor:"#fff",messageLineHeight:"150%",messageSize:"16px"}),p.value="";return}return e.hits.slice(0,Math.min(n,e.hits.length))})}const g=new m(".results a",{captionsData:"title",captionDelay:0});function f(o,n){o.innerHTML="",n.forEach(t=>{const e=`
             <a href="${t.largeImageURL}" data-lightbox="gallery">
                <div class="img-card">
                    <img src="${t.webformatURL}" width='358' height='152' alt="${t.tags}" title="${t.tags}">
                    <div class="card-info">
                        <p>Likes <span class='span-data'>${t.likes}</span></p>
                        <p>Views <span class='span-data'>${t.views}</span></p>
                        <p>Comments <span class='span-data'>${t.comments}</span></p>
                        <p>Downloads <span class='span-data'>${t.downloads}</span></p>
                    </div>
                </div>
            </a>`;o.insertAdjacentHTML("afterbegin",e)}),g.refresh()}const a=document.getElementById("photos_input"),h=document.getElementById("submit_button"),y=document.querySelector(".results"),c=document.querySelector(".loading-img");h.addEventListener("click",()=>{const o=a.value.trim();if(!o){l.warning({title:"Warning",message:"Please fill the search field first.",position:"topRight"}),a.value="";return}const n=prompt("How many images do you want me to show?","10"),t=Number(n);if(!t||t<=0){l.error({title:"Error",message:"Please enter a valid number greater than zero.",position:"topRight"});return}c.classList.add("visible"),d(o,t).then(e=>{f(y,e)}).catch(e=>{c.classList.remove("visible"),console.error("Error fetching images:",e),a.value=""}).finally(()=>{c.classList.remove("visible")})});
//# sourceMappingURL=commonHelpers.js.map
