import{S as m,i as c}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))e(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function t(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(s){if(s.ep)return;s.ep=!0;const r=t(s);fetch(s.href,r)}})();const g="44377249-dc3d438c16ab3b76144728d61";function p(a,o){const t=new URLSearchParams({key:g,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:200});return fetch(`https://pixabay.com/api/?${t.toString()}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(!e.hits||e.hits.length===0){iziToast.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:"400px",color:"#b90e0a",messageColor:"#fff",messageLineHeight:"150%",messageSize:"16px"}),input.value="";return}return e.hits.slice(0,Math.min(o,e.hits.length))})}const u=new m(".results a",{captionsData:"title",captionDelay:0});function d(a,o){a.innerHTML="",o.forEach(t=>{const e=`
             <a href="${t.largeImageURL}" data-lightbox="gallery">
                <div class="img-card">
                    <img src="${t.webformatURL}" width='358' height='152' alt="${t.tags}" title="${t.tags}">
                    <div class="card-info">
                        <p>Likes <span class='span-data'>${t.likes}</span></p>
                        <p>Views <span class='span-data'>${t.views}</span></p>
                        <p>Comments <span class='span-data'>${t.comments}</span></p>
                        <p>Downloads <span class='span-data'>${t.downloads}</span></p>
                    </div>
                </div>
            </a>`;a.insertAdjacentHTML("afterbegin",e)}),u.refresh()}const f=document.getElementById("photos_input"),h=document.getElementById("submit_button"),l=document.querySelector(".results"),i=document.querySelector(".loading-img");h.addEventListener("click",()=>{const a=f.value.trim(),o=prompt("How many images do you want me to show?","10"),t=Number(o);if(!a){console.log("Error"),l.innerHTML="";return}if(!t||t<=0){c.error({title:"Error",message:"Please enter a valid number greater than zero.",position:"topRight"});return}i.classList.add("visible"),p(a,t).then(e=>{d(l,e)}).catch(e=>{i.classList.remove("visible"),c.warning({message:"Sorry, there was an error fetching images. Please try again later.",position:"topRight",maxWidth:"400px",color:"#b90e0a",messageColor:"#fff",messageLineHeight:"150%",messageSize:"16px"}),console.error("Error fetching images:",e)}).finally(()=>{i.classList.remove("visible")})});
//# sourceMappingURL=commonHelpers.js.map
